export const SUPABASE_URL_KEYS = [
  'SUPABASE_DATABASE_URL',
  'SUPABASE_URL',
  'SUPABASE_DB_URL',
  'SUPABASE_PROJECT_URL',
  'SUPABASE_REST_URL',
  'NEXT_PUBLIC_SUPABASE_URL',
  'NEXT_PUBLIC_SUPABASE_DATABASE_URL',
  'PUBLIC_SUPABASE_URL',
]

export const SUPABASE_ANON_KEYS = [
  'SUPABASE_ANON_KEY',
  'SUPABASE_PUBLIC_ANON_KEY',
  'SUPABASE_PUBLIC_API_KEY',
  'SUPABASE_API_KEY',
  'SUPABASE_KEY',
  'NEXT_PUBLIC_SUPABASE_ANON_KEY',
  'PUBLIC_SUPABASE_PUBLISHABLE_KEY',
  'PUBLIC_SUPABASE_ANON_KEY',
]

export const SUPABASE_SERVICE_ROLE_KEYS = [
  'SUPABASE_SERVICE_ROLE_KEY',
  'SUPABASE_SERVICE_KEY',
  'SUPABASE_SERVICE_ROLE',
  'SUPABASE_SERVICE_API_KEY',
  'SUPABASE_SERVICE_ROLE_SECRET',
]

export const SUPABASE_JWT_KEYS = [
  'SUPABASE_JWT_SECRET',
  'SUPABASE_JWT',
  'NEXT_PUBLIC_SUPABASE_JWT_SECRET',
]

export const describeSupabaseKeyPresence = (env = {}) => ({
  urlKeys: SUPABASE_URL_KEYS.filter((key) => env?.[key]),
  anonKeys: SUPABASE_ANON_KEYS.filter((key) => env?.[key]),
  serviceRoleKeys: SUPABASE_SERVICE_ROLE_KEYS.filter((key) => env?.[key]),
  jwtKeys: SUPABASE_JWT_KEYS.filter((key) => env?.[key]),
})
