import { useEffect, useRef, useState } from 'react'
import { Activity, AlertTriangle, Check, CircleStop, Pause, Play, Square, UploadCloud, Volume2 } from 'lucide-react'
import SignalVisualizer from './SignalVisualizer'
import Spectrogram from './Spectrogram'

function formatTime(seconds){if(!Number.isFinite(seconds))return'0:00';const n=Math.max(0,Math.floor(seconds));return`${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`}
function formatBytes(bytes){if(!Number.isFinite(bytes))return'—';if(bytes<1024)return`${bytes} B`;const units=['KB','MB','GB','TB'];let v=bytes/1024,u=units[0];for(let i=0;i<units.length-1&&v>=1024;i+=1){v/=1024;u=units[i+1]}return`${v.toFixed(v>=10?1:2)} ${u}`}
function readAscii(v,o,l){return Array.from({length:l},(_,i)=>String.fromCharCode(v.getUint8(o+i))).join('')}
function cleanText(b){return new TextDecoder('utf-8',{fatal:false}).decode(b).replace(/\0/g,'').trim()}
function parseWavMetadata(file,buffer){const v=new DataView(buffer),m={container:'WAV',codec:'Unknown',audioFormat:null,channels:null,sampleRate:null,byteRate:null,blockAlign:null,bitsPerSample:null,dataBytes:null,duration:null,info:{}};if(v.byteLength<12||readAscii(v,0,4)!=='RIFF'||readAscii(v,8,4)!=='WAVE')return m;let o=12;while(o+8<=v.byteLength){const id=readAscii(v,o,4),size=v.getUint32(o+4,true),start=o+8,end=Math.min(v.byteLength,start+size);if(id==='fmt '&&end-start>=16){m.audioFormat=v.getUint16(start,true);m.channels=v.getUint16(start+2,true);m.sampleRate=v.getUint32(start+4,true);m.byteRate=v.getUint32(start+8,true);m.blockAlign=v.getUint16(start+12,true);m.bitsPerSample=v.getUint16(start+14,true);m.codec=m.audioFormat===1?'PCM':`WAV format ${m.audioFormat}`}else if(id==='data')m.dataBytes=size;else if(id==='LIST'&&end-start>=4&&readAscii(v,start,4)==='INFO'){let p=start+4;while(p+8<=end){const key=readAscii(v,p,4),n=v.getUint32(p+4,true),s=p+8,e=Math.min(end,s+n);if(e>s){const value=cleanText(new Uint8Array(buffer,s,e-s));if(value)m.info[key]=value}p=s+n+(n%2)}}else if(id==='bext'&&end>start){const d=cleanText(new Uint8Array(buffer,start,Math.min(256,end-start)));if(d)m.info.BEXT=d}o=start+size+(size%2)}if(m.byteRate)m.duration=m.dataBytes?m.dataBytes/m.byteRate:null;m.fileName=file.name;m.fileSize=file.size;m.mime=file.type||'audio/wav';m.lastModified=file.lastModified?new Date(file.lastModified).toLocaleString():'—';m.bitrate=m.byteRate?m.byteRate*8:null;return m}
function drawWaveform(canvas,data,progress=0){if(!canvas||!data?.length)return;const dpr=window.devicePixelRatio||1,r=canvas.getBoundingClientRect();canvas.width=Math.max(1,r.width*dpr);canvas.height=Math.max(1,r.height*dpr);const c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,r.width,r.height);const bars=Math.min(180,data.length),step=data.length/bars,gap=2,w=Math.max(1,(r.width-(bars-1)*gap)/bars),mid=r.height/2;for(let i=0;i<bars;i+=1){const s=Math.floor(i*step),e=Math.max(s+1,Math.floor((i+1)*step));let peak=0;for(let j=s;j<e;j+=1)peak=Math.max(peak,data[j]);const h=Math.max(3,peak*r.height*.88),x=i*(w+gap);c.fillStyle=i/bars<=progress?'#c99a66':'rgba(250,248,244,.25)';c.beginPath();c.roundRect(x,mid-h/2,w,h,Math.min(2,w/2));c.fill()}}

export default function AudioUploadPlayer({file,uploadProgress,uploading,processing,uploadComplete,onStop}){
 const audioRef=useRef(null),canvasRef=useRef(null),audioContextRef=useRef(null),sourceRef=useRef(null),analyserRef=useRef(null),meterFrameRef=useRef(null),seekDragRef=useRef(false)
 const [waveform,setWaveform]=useState(null),[decodedAudio,setDecodedAudio]=useState(null),[playing,setPlaying]=useState(false),[currentTime,setCurrentTime]=useState(0),[duration,setDuration]=useState(0),[metadata,setMetadata]=useState(null),[level,setLevel]=useState(0),[dbfs,setDbfs]=useState(-60),[clipping,setClipping]=useState(false),[decodeState,setDecodeState]=useState('idle'),[visualAnalyser,setVisualAnalyser]=useState(null)
 const stopMeter=()=>{cancelAnimationFrame(meterFrameRef.current);meterFrameRef.current=null;setLevel(0);setDbfs(-60);setClipping(false)}
 useEffect(()=>{if(!file)return undefined;let disposed=false;const url=URL.createObjectURL(file),audio=new Audio(url);audio.preload='metadata';audioRef.current=audio;const load=async()=>{try{setDecodeState('decoding');const buffer=await file.arrayBuffer(),parsed=parseWavMetadata(file,buffer);if(disposed)return;setMetadata(parsed);const AC=window.AudioContext||window.webkitAudioContext;if(!AC){setDecodeState('ready');return}const context=new AC(),decoded=await context.decodeAudioData(buffer.slice(0));if(disposed){await context.close().catch(()=>{});return}const channel=decoded.getChannelData(0),samples=900,block=Math.max(1,Math.floor(channel.length/samples)),peaks=new Float32Array(samples);for(let i=0;i<samples;i+=1){let peak=0;const s=i*block,e=Math.min(channel.length,s+block);for(let j=s;j<e;j+=1)peak=Math.max(peak,Math.abs(channel[j]));peaks[i]=peak}setWaveform(peaks);setDecodedAudio(decoded);setDuration(decoded.duration||parsed.duration||0);setDecodeState('ready');await context.close().catch(()=>{})}catch{if(!disposed)setDecodeState('error')}};const onLoaded=()=>setDuration(audio.duration||0),onTime=()=>setCurrentTime(audio.currentTime),onEnded=()=>{setPlaying(false);stopMeter()};audio.addEventListener('loadedmetadata',onLoaded);audio.addEventListener('timeupdate',onTime);audio.addEventListener('ended',onEnded);load();return()=>{disposed=true;audio.pause();stopMeter();audio.removeEventListener('loadedmetadata',onLoaded);audio.removeEventListener('timeupdate',onTime);audio.removeEventListener('ended',onEnded);audioRef.current=null;sourceRef.current=null;analyserRef.current=null;setVisualAnalyser(null);if(audioContextRef.current)audioContextRef.current.close().catch(()=>{});audioContextRef.current=null;URL.revokeObjectURL(url)}},[file])
 useEffect(()=>{const draw=()=>drawWaveform(canvasRef.current,waveform,duration?currentTime/duration:0);draw();window.addEventListener('resize',draw);return()=>window.removeEventListener('resize',draw)},[waveform,currentTime,duration])
 if(!file)return null
 const ensureMeter=async()=>{if(!audioRef.current)return;if(!audioContextRef.current){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;const context=new AC(),source=context.createMediaElementSource(audioRef.current),analyser=context.createAnalyser();analyser.fftSize=1024;analyser.smoothingTimeConstant=.72;source.connect(analyser);analyser.connect(context.destination);audioContextRef.current=context;sourceRef.current=source;analyserRef.current=analyser;setVisualAnalyser(analyser)}await audioContextRef.current.resume();const analyser=analyserRef.current,data=new Float32Array(analyser.fftSize);const tick=()=>{if(!analyserRef.current||!audioRef.current)return;analyser.getFloatTimeDomainData(data);let peak=0;for(let i=0;i<data.length;i+=1)peak=Math.max(peak,Math.abs(data[i]));setLevel(Math.min(1,peak));setDbfs(Math.max(-60,peak>0?20*Math.log10(peak):-60));setClipping(peak>=.98);if(!audioRef.current.paused&&!audioRef.current.ended)meterFrameRef.current=requestAnimationFrame(tick)};cancelAnimationFrame(meterFrameRef.current);meterFrameRef.current=requestAnimationFrame(tick)}
 const play=async()=>{if(!audioRef.current)return;await audioRef.current.play();setPlaying(true);await ensureMeter()},pause=()=>{audioRef.current?.pause();setPlaying(false);stopMeter()},stop=()=>{if(!audioRef.current)return;audioRef.current.pause();audioRef.current.currentTime=0;setCurrentTime(0);setPlaying(false);stopMeter()},seekRatio=ratio=>{if(!audioRef.current||!duration)return;const next=Math.max(0,Math.min(1,ratio))*duration;audioRef.current.currentTime=next;setCurrentTime(next)},seek=e=>{const r=e.currentTarget.getBoundingClientRect();seekRatio((e.clientX-r.left)/r.width)},pointerRatio=e=>{const r=e.currentTarget.getBoundingClientRect();seekRatio((e.clientX-r.left)/r.width)},startSeek=e=>{seekDragRef.current=true;e.currentTarget.setPointerCapture?.(e.pointerId);pointerRatio(e);e.preventDefault()},moveSeek=e=>{if(!seekDragRef.current)return;pointerRatio(e)},endSeek=e=>{seekDragRef.current=false;if(e.currentTarget.hasPointerCapture?.(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)}
 const progress=Math.min(100,Number(uploadProgress)||0),bitrate=metadata?.bitrate?`${(metadata.bitrate/1000).toFixed(1)} kbps`:'—',infoRows=[['Format',metadata?`${metadata.container} · ${metadata.codec}`:'Decoding…'],['Sample rate',metadata?.sampleRate?`${metadata.sampleRate.toLocaleString()} Hz`:'—'],['Channels',metadata?.channels?String(metadata.channels):'—'],['Bit depth',metadata?.bitsPerSample?`${metadata.bitsPerSample}-bit`:'—'],['Bitrate',bitrate],['Duration',duration?formatTime(duration):'—'],['File size',formatBytes(file.size)],['MIME type',file.type||'audio/wav'],['Modified',metadata?.lastModified||'—']]
 const player=<div className="vv-audio-player vv-player-ready"><div className="vv-audio-head"><span className="vv-audio-file" title={file.name}>{file.name}</span><span className="vv-muted mono">{formatTime(currentTime)} / {formatTime(duration)}</span></div><button type="button" className="vv-waveform-hit" onClick={seek} onPointerDown={startSeek} onPointerMove={moveSeek} onPointerUp={endSeek} onPointerCancel={endSeek} aria-label="Seek through uploaded audio by dragging"><canvas ref={canvasRef}/></button><div className="vv-audio-controls"><button type="button" onClick={playing?pause:play}>{playing?<Pause size={15}/>:<Play size={15}/>} {playing?'Pause':'Play'}</button><button type="button" onClick={stop}><Square size={13}/> Stop</button><span className="vv-audio-hint">{decodeState==='decoding'?'Decoding metadata…':'Drag waveform to seek'}</span></div></div>
 return <div className="vv-audio-upload">{(uploading||processing||uploadComplete)&&<div className="vv-upload-state"><div className="vv-upload-top"><span>{processing?<Activity size={15} className="vv-spin-soft"/>:uploadComplete?<Check size={15}/>:<UploadCloud size={15}/>} {processing?'Analysis in progress':uploadComplete?'Upload complete':'Uploading audio'}</span><strong>{processing?'Server analysis':`${Math.round(progress)}%`}</strong></div><div className="vv-upload-track"><div className={`vv-upload-fill ${uploadComplete?'complete':''}`} style={{width:`${progress}%`}}/></div><div className="vv-upload-status-line">{processing?'The upload is finished. Analysis state is now driven by live server diagnostics.':uploadComplete?'Upload finished. Waiting for the analysis pipeline.':'Transferring the selected file…'}</div>{(uploading||processing)&&<button type="button" className="vv-stop-analysis" onClick={onStop}><CircleStop size={15}/> Stop analysis</button>}<div className="vv-upload-wave" aria-hidden="true">{Array.from({length:34},(_,i)=><i key={i} style={{'--h':`${22+(i*17)%58}%`,'--d':`${i*24}ms`}}/>)}</div></div>}
 {!uploading&&!processing&&<><>{player}</><div className="vv-playback-visualizer"><SignalVisualizer analyser={visualAnalyser} playing={playing} mode="radial" label="Live frequency visualization of uploaded audio playback"/><div className="vv-visualizer-caption"><strong>LIVE SIGNAL</strong> · playback frequency field</div></div>{decodeState==='ready'&&<Spectrogram audioBuffer={decodedAudio} analyser={visualAnalyser} playing={playing} currentTime={currentTime} duration={duration} sampleRate={metadata?.sampleRate||48000} onSeek={seekRatio}/>}</>}
 <div className="vv-file-info-panel"><div className="vv-file-info-head"><div><span className="vv-eyebrow">FILE INFORMATION</span><h3 title={file.name}>{file.name}</h3></div><span className="vv-file-ready">{decodeState==='ready'?'DECODED':decodeState==='error'?'PARTIAL':'DECODING'}</span></div><div className="vv-file-info-grid">{infoRows.map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>{Object.keys(metadata?.info||{}).length>0&&<div className="vv-wav-tags"><span className="vv-eyebrow">EMBEDDED WAV METADATA</span>{Object.entries(metadata.info).map(([key,value])=><div key={key}><span>{key}</span><strong>{value}</strong></div>)}</div>}</div>
 <div className="vv-clipping-meter"><div className="vv-meter-head"><span><Volume2 size={15}/> Live playback level</span><strong className={clipping?'clip':''}>{clipping?'CLIP':`${dbfs.toFixed(1)} dBFS`}</strong></div><div className="vv-meter-track"><div className="vv-meter-fill" style={{width:`${level*100}%`}}/></div><div className="vv-meter-scale"><span>−60</span><span>−18</span><span>−6</span><span>0 dBFS</span></div>{clipping&&<div className="vv-clip-warning"><AlertTriangle size={13}/> Digital clipping detected during playback</div>}</div></div>
}
