import { useEffect, useState } from 'react'
import { Activity, AlertTriangle, BookOpen, CheckCircle2, ChevronDown, ChevronRight, Circle, CircleCheck, Code2, FileAudio, Globe2, Images, Info, ListChecks, LogOut, Menu, Play, RefreshCw, Terminal, UserRound, Waves, X, XCircle } from 'lucide-react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { analyzeCaseSource, API_BASE, createAnalysisCase, getCasePlaybackUrl, getAnalysisCase, getDiagnosticErrors, getDiagnosticEvents, getHealth, listAnalysisCases, uploadCaseSource } from '../lib/api'
import Button from './ui/Button'
import Card from './ui/Card'
import Sheet from './ui/Sheet'
import ThemeToggle, { applyTheme, getStoredTheme } from './ui/ThemeToggle'
import Toast from './ui/Toast'
import CaseAnalysisWorkspace from './CaseAnalysisWorkspace'
import SiteHeader from './SiteHeader'
import './DeveloperConsole.css'

const DOCS = {
  methodology: 'https://github.com/darenprince/darenprince-author/blob/main/VoxVector/docs/ANALYSIS_METHODS.md',
  pipeline: 'https://github.com/darenprince/darenprince-author/blob/main/VoxVector/docs/ANALYSIS_PIPELINE.md',
  architecture: 'https://github.com/darenprince/darenprince-author/blob/main/VoxVector/docs/ARCHITECTURE.md',
  mvp: 'https://github.com/darenprince/darenprince-author/blob/main/VoxVector/docs/MVP_BUILD_PLAN.md',
  methodsIndex: 'https://github.com/darenprince/darenprince-author/blob/main/VoxVector/docs/MASTER_METHOD_INDEX.md',
  capability: 'https://github.com/darenprince/darenprince-author/blob/main/VoxVector/docs/CAPABILITY_STATUS.md',
}

const PUBLIC = {
  home: '/voxvector/',
  developer: '/voxvector/developer/',
  methods: '/voxvector/methods.html',
  pipeline: '/voxvector/pipeline.html',
  imageIndex: '/voxvector/image-index/',
  sitemap: '/voxvector/sitemap.xml',
}

const phases = [
  { id: 'P0', title: 'Case spine', detail: 'Identity persistence provenance storage and lifecycle.', tasks: [['case-schema', 'Canonical analysis case schema', 'backend'], ['intake-persist', 'Persist source metadata and provenance', 'backend'], ['lifecycle', 'Persist request and stage lifecycle', 'backend']] },
  { id: 'P1', title: 'Recording workspace', detail: 'Move from upload to usable synchronized audio.', tasks: [['upload', 'Production upload flow and validation', 'frontend + API'], ['playback', 'Audio playback and shared playhead', 'frontend'], ['waveform', 'Waveform renderer from source audio', 'frontend'], ['regions', 'Region selection and timestamp navigation', 'frontend']] },
  { id: 'P2', title: 'Real pipeline', detail: 'Expose actual backend processing state and observations.', tasks: [['pipeline', '21 stage pipeline status mapping', 'backend + frontend'], ['quality', 'Eligibility and recording quality state', 'backend'], ['tracks', 'Pitch intensity spectral and temporal tracks', 'backend + frontend'], ['events', 'Timestamped evidence events', 'backend']] },
  { id: 'P3', title: 'Speaker + transcript', detail: 'Turn audio into a speaker-aware timestamped transcript.', tasks: [['speakers', 'Speaker segmentation and diarization', 'backend'], ['asr', 'Production ASR integration', 'backend'], ['transcript', 'Persist transcript timestamps and confidence', 'backend'], ['alignment', 'Audio and transcript synchronization', 'frontend + backend']] },
  { id: 'P4', title: 'Evidence workspace', detail: 'Make every observation inspectable and traceable.', tasks: [['evidence-schema', 'Normalized evidence records with provenance', 'backend'], ['timeline', 'Evidence timeline linked to audio', 'frontend'], ['explorer', 'Evidence Explorer filters and playback', 'frontend'], ['synthesis', 'Convergence and conflict representation', 'backend + frontend']] },
  { id: 'P5', title: 'Assessment + report', detail: 'Connect evidence to assessment reporting and case history.', tasks: [['candidate', 'Candidate classification trace', 'backend'], ['assessment', 'Assessment surface from canonical result', 'frontend'], ['report', 'Structured report generation', 'backend + frontend'], ['history', 'Persist and reopen cases', 'backend + frontend']] },
  { id: 'P6', title: 'Validation + hardening', detail: 'Move the product spine into reproducible validated operation.', tasks: [['eval', 'Evaluation harness and speaker-disjoint datasets', 'research'], ['calibration', 'Calibration and uncertainty analysis', 'research'], ['e2e', 'Browser end-to-end verification', 'QA'], ['security', 'Media access retention and deletion controls', 'security + backend']] },
]

const unwrap = result => result?.payload?.case || result?.payload?.data || result?.payload || {}
const caseId = result => unwrap(result)?.case_id || result?.payload?.case_id || ''
const sourceFrom = result => unwrap(result)?.source || result?.payload?.source || unwrap(result)
const latestRun = data => data?.runs?.find(run => run.run_id === data.current_run_id) || data?.runs?.at(-1) || null
const readChecks = () => { try { return JSON.parse(localStorage.getItem('voxvector-mvp-checks') || '{}') } catch { return {} } }

export default function DeveloperConsole({ session, signOut }) {
  const [section, setSection] = useState('dashboard')
  const [mobileOpen, setMobileOpen] = useState(false)
  const [theme, setTheme] = useState(getStoredTheme)
  const [checks, setChecks] = useState(readChecks)
  const [selectedCaseId, setSelectedCaseId] = useState('')
  const [title, setTitle] = useState('')
  const [file, setFile] = useState(null)
  const [progress, setProgress] = useState(0)
  const [source, setSource] = useState(null)
  const [playbackUrl, setPlaybackUrl] = useState('')
  const [error, setError] = useState('')
  const [toast, setToast] = useState(null)
  const [profileOpen, setProfileOpen] = useState(false)
  const queryClient = useQueryClient()

  useEffect(() => { applyTheme(theme) }, [theme])
  useEffect(() => { localStorage.setItem('voxvector-mvp-checks', JSON.stringify(checks)) }, [checks])
  useEffect(() => { if (!toast) return undefined; const timer = window.setTimeout(() => setToast(null), 4800); return () => window.clearTimeout(timer) }, [toast])

  const health = useQuery({ queryKey: ['health'], queryFn: getHealth, refetchInterval: 30000 })
  const cases = useQuery({ queryKey: ['cases'], queryFn: () => listAnalysisCases(session.access_token), enabled: Boolean(session.access_token) })
  const current = useQuery({ queryKey: ['case', selectedCaseId], queryFn: () => getAnalysisCase(session.access_token, selectedCaseId), enabled: Boolean(selectedCaseId), refetchInterval: section === 'api' || section === 'workspace' ? 3000 : false })
  const errors = useQuery({ queryKey: ['diagnostic-errors'], queryFn: () => getDiagnosticErrors(session.access_token), enabled: section === 'errors' })
  const logs = useQuery({ queryKey: ['diagnostic-events'], queryFn: () => getDiagnosticEvents(session.access_token, { days: 2, limit: 100 }), enabled: section === 'logs', refetchInterval: section === 'logs' ? 2500 : false })

  const notify = (type, titleText, message = '', extra = {}) => setToast({ type, title: titleText, message, ...extra })
  const create = useMutation({ mutationFn: () => createAnalysisCase(session.access_token, title.trim()), onSuccess: result => { const id = caseId(result); setSelectedCaseId(id); setTitle(''); setSource(null); setPlaybackUrl(''); setError(''); setProgress(0); queryClient.invalidateQueries({ queryKey: ['cases'] }); notify('success', 'Case Created', 'The analysis case is ready for recording intake.') }, onError: e => { setError(e.message); notify('error', 'Case Creation Failed', e.message, { requestId: e.requestId }) } })
  const upload = useMutation({ mutationFn: ({ uploadFile }) => uploadCaseSource(session.access_token, selectedCaseId, uploadFile, setProgress, { onState: state => { if (state?.state === 'processing') notify('info', 'Upload Received', 'The API is validating and persisting the recording.', { requestId: state.requestId }) } }), onSuccess: result => { setSource(sourceFrom(result)); setFile(sourceFrom(result)); setError(''); setProgress(100); queryClient.invalidateQueries({ queryKey: ['case', selectedCaseId] }); queryClient.invalidateQueries({ queryKey: ['cases'] }); notify('success', 'Recording Uploaded', 'The WAV source has been persisted to the selected case.', { requestId: result.requestId }) }, onError: e => { setProgress(0); setError(e.message); notify(e.code === 'UPLOAD_ABORTED' ? 'warning' : 'error', e.code === 'UPLOAD_ABORTED' ? 'Upload Cancelled' : 'Upload Failed', e.message, { requestId: e.requestId }) } })
  const playback = useMutation({ mutationFn: () => getCasePlaybackUrl(session.access_token, selectedCaseId, source?.source_id), onSuccess: result => { setPlaybackUrl(unwrap(result)?.url || result?.payload?.url || ''); notify('success', 'Secure Playback Ready', 'The private recording URL has been prepared.') }, onError: e => { setError(e.message); notify('error', 'Playback Failed', e.message, { requestId: e.requestId }) } })
  const analyze = useMutation({ mutationFn: () => analyzeCaseSource(session.access_token, selectedCaseId, source?.source_id), onSuccess: result => { setError(''); queryClient.setQueryData(['case', selectedCaseId], result); queryClient.invalidateQueries({ queryKey: ['cases'] }); setSection('workspace'); notify('success', 'Analysis Run Completed', 'The case workspace now has the persisted pipeline state.', { requestId: result?.requestId }) }, onError: e => { setError(e.message); notify('error', 'Analysis Failed', e.message, { requestId: e.requestId }) } })

  const total = phases.reduce((n, p) => n + p.tasks.length, 0)
  const complete = Object.values(checks).filter(Boolean).length
  const percent = Math.round((complete / total) * 100)
  const data = unwrap(current.data)
  const run = latestRun(data)
  const activeSource = source || data?.sources?.[0]
  const list = cases.data?.payload?.cases || (Array.isArray(cases.data?.payload) ? cases.data.payload : [])
  const choose = id => { setSection(id); setMobileOpen(false); setProfileOpen(false) }
  const selectCase = id => { setSelectedCaseId(id); setSource(null); setPlaybackUrl(''); setProgress(0); setError('') }

  const user = session?.user || {}
  const metadata = user.user_metadata || {}
  const avatarUrl = metadata.avatar_url || metadata.picture || ''
  const displayName = metadata.full_name || metadata.name || user.email?.split('@')[0] || 'Developer'
  const initials = displayName.split(/\s+/).filter(Boolean).slice(0, 2).map(part => part[0]).join('').toUpperCase() || 'D'
  const avatar = <span className="inline-flex h-9 w-9 shrink-0 items-center justify-center overflow-hidden rounded-full border border-white/15 bg-white/[.08] text-[11px] font-bold text-white/75">{avatarUrl ? <img src={avatarUrl} alt="" className="h-full w-full object-cover" referrerPolicy="no-referrer"/> : initials}</span>
  const profileMenu = <div className="relative hidden md:block"><button type="button" className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.035] p-1 pr-2 transition hover:border-white/20 hover:bg-white/[.06]" onClick={() => setProfileOpen(value => !value)} aria-haspopup="menu" aria-expanded={profileOpen} aria-label="Open developer profile menu">{avatar}<span className="hidden lg:block max-w-[150px] truncate text-xs font-medium text-white/65">{displayName}</span><ChevronDown size={13} className={`text-white/35 transition-transform ${profileOpen ? 'rotate-180' : ''}`}/></button>{profileOpen && <div role="menu" className="absolute right-0 top-[calc(100%+10px)] z-[80] w-64 border border-white/10 bg-[#101010]/98 p-2 shadow-[0_20px_60px_rgba(0,0,0,.45)] backdrop-blur-xl"><div className="flex items-center gap-3 border-b border-white/10 px-2 py-3">{avatar}<div className="min-w-0"><div className="truncate text-sm font-semibold text-white">{displayName}</div><div className="truncate text-[11px] text-white/40">{user.email}</div></div></div><button type="button" role="menuitem" className="mt-2 flex w-full items-center gap-2 px-2 py-2.5 text-left text-sm text-white/65 transition hover:bg-white/[.05] hover:text-white" onClick={() => choose('profile')}><UserRound size={15}/>Profile</button><button type="button" role="menuitem" className="flex w-full items-center gap-2 px-2 py-2.5 text-left text-sm text-red-300/80 transition hover:bg-red-400/[.07] hover:text-red-200" onClick={() => signOut()}><LogOut size={15}/>Sign out</button></div>}</div>
  const headerActions = <><a className="hidden sm:inline-flex items-center gap-2 text-xs text-[var(--vv-muted)] no-underline hover:text-[var(--vv-text)]" href={DOCS.methodology} target="_blank" rel="noreferrer"><BookOpen size={14}/> Methodology</a><ThemeToggle theme={theme} onThemeChange={setTheme}/>{profileMenu}</>
  const mobileHeaderButton = <Button variant="ghost" size="icon" onClick={() => setMobileOpen(true)} aria-label="Open navigation"><Menu size={19}/></Button>

  return <div className="vv-app">
    <SiteHeader actions={headerActions} mobileMenuButton={mobileHeaderButton} />
    <Toast toast={toast} onDismiss={() => setToast(null)} />
    <div className="vv-shell"><aside className="vv-sidebar"><Sidebar section={section} choose={choose}/></aside><Sheet open={mobileOpen} onOpenChange={setMobileOpen} ariaLabel="Developer console navigation"><div className="vv-sheet-head"><span className="vv-eyebrow">Console</span><Button variant="ghost" size="icon" onClick={() => setMobileOpen(false)} aria-label="Close navigation"><X size={18}/></Button></div><Sidebar section={section} choose={choose}/><div className="mt-4 border-t border-[var(--vv-border)] pt-4"> <button type="button" className="flex w-full items-center gap-3 px-2 py-2 text-left" onClick={() => choose('profile')}>{avatar}<span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{displayName}</span><span className="block truncate text-[10px] text-[var(--vv-muted)]">{user.email}</span></span><UserRound size={16}/></button><button type="button" className="mt-1 flex w-full items-center gap-2 px-2 py-2 text-left text-sm text-red-300/80" onClick={() => signOut()}><LogOut size={15}/>Sign out</button></div></Sheet><main className="vv-main">
      {section === 'dashboard' && <Dashboard health={health} percent={percent} complete={complete} total={total} openCases={() => choose('api')} openPlan={() => choose('mvp')} openWorkspace={() => choose('workspace')}/>} 
      {section === 'api' && <CaseWorkbench list={list} selectedCaseId={selectedCaseId} setSelectedCaseId={selectCase} title={title} setTitle={setTitle} create={create} file={file} setFile={setFile} upload={upload} progress={progress} source={activeSource} data={data} playback={playback} playbackUrl={playbackUrl} analyze={analyze} run={run} error={error} refresh={() => current.refetch()} openWorkspace={() => choose('workspace')} notify={notify}/>} 
      {section === 'workspace' && <CaseAnalysisWorkspace caseResult={current.data} playbackUrl={playbackUrl} file={file} onRefresh={() => current.refetch()}/>} 
      {section === 'mvp' && <MvpBoard checks={checks} setChecks={setChecks} percent={percent} complete={complete} total={total}/>} 
      {section === 'docs' && <Docs/>}
      {section === 'errors' && <ErrorPanel query={errors}/>} 
      {section === 'logs' && <LogPanel query={logs}/>} 
      {section === 'profile' && <Profile session={session} signOut={signOut} avatar={avatar}/>} 
    </main></div>
  </div>
}

function Sidebar({ section, choose }) { const items = [['dashboard','Dashboard',Activity],['api','Case Workbench',Code2],['workspace','Analysis Workspace',Waves],['mvp','MVP Build Plan',ListChecks],['docs','Methodology & Docs',BookOpen],['errors','Error Reports',AlertTriangle],['logs','Live Logs',Terminal],['profile','Profile',UserRound]]; return <div className="vv-sidebar-content"><div className="vv-sidebar-label">Build</div>{items.slice(0,5).map(([id,label,Icon]) => <button key={id} className={`vv-nav-item ${section === id ? 'active' : ''}`} onClick={() => choose(id)}><Icon size={17}/>{label}{id === 'mvp' && <span className="ml-auto text-[9px] font-bold tracking-[.1em] text-[var(--vv-accent-bright)]">MVP</span>}</button>)}<div className="vv-sidebar-divider"/><div className="vv-sidebar-label">Observe</div>{items.slice(5).map(([id,label,Icon]) => <button key={id} className={`vv-nav-item ${section === id ? 'active' : ''}`} onClick={() => choose(id)}><Icon size={17}/>{label}</button>)}<div className="vv-sidebar-divider"/><div className="vv-sidebar-label">Source</div><a className="vv-nav-item" href={DOCS.methodology} target="_blank" rel="noreferrer"><BookOpen size={17}/>Methodology</a><a className="vv-nav-item" href={DOCS.pipeline} target="_blank" rel="noreferrer"><Waves size={17}/>21 stage pipeline</a><a className="vv-nav-item" href="https://github.com/darenprince/darenprince-author/tree/main/voxvector" target="_blank" rel="noreferrer"><Code2 size={17}/>Frontend source</a><div className="vv-sidebar-divider"/><div className="vv-sidebar-label">Site</div><a className="vv-nav-item" href={PUBLIC.home}>Public landing</a><a className="vv-nav-item" href={PUBLIC.methods}><BookOpen size={17}/>Methods page</a><a className="vv-nav-item" href={PUBLIC.pipeline}><Waves size={17}/>Pipeline page</a><a className="vv-nav-item" href={PUBLIC.imageIndex}><Images size={17}/>Image index</a><a className="vv-nav-item" href={PUBLIC.sitemap}><Code2 size={17}/>Sitemap</a></div> }

function PageTitle({ eyebrow, title, action }) { return <div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><div className="vv-eyebrow">{eyebrow}</div><h1 className="mt-1 text-2xl font-semibold tracking-tight">{title}</h1></div>{action}</div> }
function Metric({ label, value, detail, state }) { return <Card><div className="vv-eyebrow">{label}</div><div className="mt-2 text-xl font-semibold">{value}</div><div className="mt-1 text-xs text-[var(--vv-muted)]">{detail}</div><div className={`mt-3 vv-dot ${state}`}/></Card> }
function Dashboard({ health, percent, complete, total, openCases, openPlan, openWorkspace }) { const h = health.data?.payload || {}; const online = health.isSuccess && h?.status === 'ok'; const pipeline = h?.pipeline_build || {}; const qa = h?.testing || {}; const pipelineState = pipeline.total === 21 ? `${pipeline.implemented_foundations || 0}/21` : '—'; return <div><PageTitle eyebrow="BUILD CONTROL" title="Developer Overview" action={<Button variant="secondary" onClick={() => health.refetch()}><RefreshCw size={14}/> Refresh</Button>}/><div className="vv-metrics"><Metric label="API" value={health.isPending ? 'CHECKING' : online ? 'ONLINE' : 'CHECK'} detail={API_BASE} state={online ? 'healthy' : 'warning'}/><Metric label="Runtime" value={h?.runtime_self_test || '—'} detail={h?.source_revision?.slice?.(0,12) || 'source revision'} state={h?.runtime_self_test === 'passed' ? 'healthy' : 'warning'}/><Metric label="21-stage build" value={pipelineState} detail={`${pipeline.queued || 0} queued · ${pipeline.conditional_or_not_invoked || 0} conditional`} state={pipeline.total === 21 ? 'healthy' : 'warning'}/><Metric label="QA baseline" value={qa?.historical_backend_baseline?.passed ? `${qa.historical_backend_baseline.passed} passed` : '—'} detail="historical baseline · current QA pending" state="warning"/></div><div className="vv-content-grid"><section className="vv-panel"><div className="vv-panel-head"><h2>Next Engineering Move</h2><span>case first</span></div><p className="vv-copy">Create a real case then upload a recording. The same case becomes the source of playback analysis pipeline state and the Analysis Workspace.</p><div className="flex flex-wrap gap-2 mt-5"><Button variant="accent" onClick={openCases}><FileAudio size={15}/> Open Case Workbench</Button><Button variant="secondary" onClick={openWorkspace}><Waves size={15}/> Analysis Workspace</Button><Button variant="secondary" onClick={openPlan}><ListChecks size={15}/> MVP Build Plan</Button></div></section><section className="vv-panel"><div className="vv-panel-head"><h2>Runtime Fingerprint</h2><span>/health</span></div><pre className="vv-code">{JSON.stringify(h, null, 2)}</pre></section></div><section className="vv-panel mt-4"><div className="vv-panel-head"><h2>Canonical Links</h2><span>repository</span></div><div className="grid gap-2 sm:grid-cols-3"><DocLink title="Methodology" href={DOCS.methodology} detail="Analysis methods"/><DocLink title="Pipeline" href={DOCS.pipeline} detail="Canonical 21 stage pipeline"/><DocLink title="Architecture" href={DOCS.architecture} detail="System boundaries"/></div></section></div> }

function CaseWorkbench({ list, selectedCaseId, setSelectedCaseId, title, setTitle, create, file, setFile, upload, progress, source, data, playback, playbackUrl, analyze, run, error, refresh, openWorkspace, notify }) {
  const canUpload = Boolean(selectedCaseId && file && !upload.isPending)
  const canAnalyze = Boolean(selectedCaseId && source?.source_id && !analyze.isPending)
  const onFileChange = event => {
    const selected = event.target.files?.[0] || null
    setProgress(0)
    setFile(selected)
    if (!selected) return
    const filename = String(selected.name || '').toLowerCase()
    const mime = String(selected.type || '').toLowerCase()
    if (!filename.endsWith('.wav') && !mime.includes('wav')) {
      setFile(null)
      event.target.value = ''
      notify('error', 'Unsupported Recording', 'Choose a WAV file. The picker is filtered to compatible audio where the browser supports the filter.')
    } else if (selected.size <= 0) {
      setFile(null)
      event.target.value = ''
      notify('error', 'Empty Recording', 'The selected audio file contains no data.')
    }
  }
  const workflowStep = !selectedCaseId ? 1 : !source?.source_id ? 2 : 3
  const nextStep = !selectedCaseId ? 'Create a case' : !file ? 'Choose a WAV recording' : !source?.source_id ? 'Upload the recording' : 'Run analysis'
  const handleUpload = () => {
    const selectedFile = file || document.getElementById('audio-file')?.files?.[0] || null
    if (!selectedFile) {
      notify('warning', 'Choose Recording', 'Select a WAV recording before uploading it to this case.')
      return
    }
    setFile(selectedFile)
    upload.mutate({ uploadFile: selectedFile })
  }
  return <div>
    <PageTitle eyebrow="CASE WORKBENCH" title="Build a Real Analysis Case" action={<Button variant="secondary" onClick={refresh}><RefreshCw size={14}/> Refresh</Button>}/>
    <section className="mb-4 border border-[var(--vv-border)] bg-[var(--vv-surface)] px-4 py-3 sm:px-5" aria-label="Case workflow">
      <div className="mb-2 text-[10px] font-bold uppercase tracking-[.16em] text-[var(--vv-muted)]">Case Workflow</div>
      <div className="grid grid-cols-3 gap-2">
        {[[1,'Create Case','Define the case'],[2,'Upload Recording','Add WAV source'],[3,'Analyze','Open evidence workspace']].map(([number,label,detail]) => <div key={number} className={`min-w-0 border-t-2 px-1 pt-2 ${workflowStep === number ? 'border-white text-white' : workflowStep > number ? 'border-emerald-400/70 text-white/70' : 'border-white/10 text-white/35'}`} aria-current={workflowStep === number ? 'step' : undefined}><div className="text-[11px] font-semibold">{number}. {label}</div><div className="mt-0.5 text-[10px] text-white/50">{detail}</div></div>)}
      </div>
      <div className="mt-3 flex items-center gap-2 text-xs text-white/55"><span className="h-1.5 w-1.5 rounded-full bg-white" aria-hidden="true"/> Next: <strong className="text-white">{nextStep}</strong></div>
    </section>
    <section className="vv-panel mb-4"><div className="vv-panel-head"><h2>1 · Analysis Case</h2><span>durable</span></div><div className="grid min-w-0 gap-3 md:grid-cols-[minmax(0,1fr)_auto]"><div className="min-w-0"><label className="vv-field-label" htmlFor="case-title">New Case Title</label><input id="case-title" className="vv-input w-full min-w-0 max-w-full" value={title} onChange={e => setTitle(e.target.value)} placeholder="Interview analysis"/></div><Button variant="accent" className="w-full self-end md:w-auto" onClick={() => create.mutate()} disabled={create.isPending || !title.trim()}><CircleCheck size={15}/> {create.isPending ? 'Creating…' : 'Create Case'}</Button></div><div className="mt-4 min-w-0"><label className="vv-field-label" htmlFor="case-select">Existing Cases</label><select id="case-select" className="vv-input w-full min-w-0 max-w-full" value={selectedCaseId} onChange={e => setSelectedCaseId(e.target.value)}><option value="">Select a case</option>{list.map(item => <option key={item.case_id} value={item.case_id}>{item.title || 'Untitled case'} · {item.case_id?.slice(0,8)}</option>)}</select></div>{data?.case_id && <div className="mt-4 flex min-w-0 items-center gap-3 vv-status-row"><CheckCircle2 size={15}/><span className="min-w-0 flex-1 truncate">{data.title || data.case_id}</span><span className="shrink-0 text-xs text-white/55">{data.status || 'Created'}</span></div>}</section>
    <section className="vv-panel mb-4"><div className="vv-panel-head"><div className="flex items-center gap-2"><h2>2 · File Upload</h2><FileInfo/></div><span>{source ? 'Source Ready' : 'WAV Intake'}</span></div><div className="grid min-w-0 gap-4 md:grid-cols-[minmax(0,1fr)_auto]"><div className="min-w-0"><label className="vv-field-label" htmlFor="audio-file">Recording</label><input id="audio-file" className="vv-input block w-full min-w-0 max-w-full" type="file" accept=".wav,audio/wav,audio/x-wav,audio/wave" onChange={onFileChange} disabled={!selectedCaseId}/>{file && <p className="vv-copy mt-2 break-words">{file.name} · {(file.size/1024/1024).toFixed(2)} MB</p>}<p className="mt-2 text-[11px] text-[var(--vv-muted)]">Compatible Files: PCM WAV · up to 250 MB · sample rate up to 48 kHz</p></div><Button variant="accent" className={`w-full self-end md:w-auto md:min-w-[150px] ${selectedCaseId && !upload.isPending ? 'ring-1 ring-white/10' : ''}`} onClick={handleUpload} disabled={!selectedCaseId || upload.isPending}>{upload.isPending ? `Uploading ${Math.round(progress)}%` : 'Upload Source'}</Button></div>{upload.isPending && <div className="mt-4 h-2 overflow-hidden rounded-full bg-white/5"><div className="h-full bg-[var(--vv-accent)] transition-all" style={{width:`${progress}%`}}/></div>}{source && <div className="vv-data-grid mt-4"><Data label="Source" value={source.source_id?.slice(0,12)}/><Data label="SHA-256" value={source.sha256?.slice(0,16)}/><Data label="Sample Rate" value={source.sample_rate ? `${source.sample_rate} Hz` : '—'}/><Data label="Duration" value={source.duration_seconds ? `${Number(source.duration_seconds).toFixed(2)} s` : '—'}/></div>}</section>
    <section className="vv-panel mb-4"><div className="vv-panel-head"><h2>3 · Playback + Analysis</h2><span>{run?.status || 'Ready'}</span></div>{playbackUrl && <audio className="mb-4 w-full" controls src={playbackUrl}/>}<div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => playback.mutate()} disabled={!source?.source_id || playback.isPending}><Play size={15}/> {playback.isPending ? 'Preparing…' : 'Open Secure Playback'}</Button><Button variant="accent" onClick={() => analyze.mutate()} disabled={!canAnalyze}>{analyze.isPending ? 'Running Canonical Pipeline…' : 'Run Analysis'}</Button><Button variant="secondary" onClick={openWorkspace} disabled={!selectedCaseId}><Waves size={15}/> Open Analysis Workspace</Button></div>{run && <RunState run={run}/>}</section>{error && <section className="vv-panel"><div className="vv-status-row error"><XCircle size={16}/><span>{error}</span></div></section>}
  </div>
}

function FileInfo() { const [open, setOpen] = useState(false); return <div className="relative"><button type="button" aria-label="Show compatible recording information" aria-expanded={open} onClick={() => setOpen(value => !value)} className="inline-flex h-6 w-6 items-center justify-center rounded-full border border-white/15 text-white/55 transition hover:border-white/30 hover:text-white"><Info size={14}/></button>{open && <div className="absolute left-0 top-8 z-40 w-[min(330px,calc(100vw-3rem))] border border-white/10 bg-[#111]/98 p-4 text-xs text-white/65 shadow-[0_20px_50px_rgba(0,0,0,.45)] backdrop-blur-xl"><div className="font-semibold text-white">Compatible Recordings</div><p className="mt-2 leading-5">The current intake accepts PCM WAV audio only. Maximum file size is 250 MB and sample rate is limited to 48 kHz.</p><div className="mt-3 border-t border-white/10 pt-3 text-[11px] text-white/45">Other formats are intentionally filtered out because the current runtime decoder supports WAV input.</div></div>}</div> }

function RunState({ run }) { const stages = run.stages || run.stage_states || []; const build = run.pipeline_build || {}; const testing = run.testing || {}; return <div className="mt-5"><div className="vv-panel-head"><h3>Pipeline Run</h3><span>{run.run_id?.slice(0,12)}</span></div><div className="vv-data-grid"><Data label="Status" value={run.status}/><Data label="Request" value={run.request_id?.slice(0,12)}/><Data label="Pipeline" value={run.pipeline_version}/><Data label="Stages" value={`${build.completed ?? stages.filter(stage => ['complete','completed','success','succeeded'].includes(stage.status)).length}/21`}/><Data label="Pending" value={build.pending ?? '—'}/><Data label="Not Run" value={build.not_run ?? '—'}/><Data label="Failed" value={build.failed ?? 0}/><Data label="QA" value={testing?.current_commit_qa || 'Not Reported'}/></div>{testing?.historical_backend_baseline && <p className="vv-copy mt-3">Historical backend baseline: {testing.historical_backend_baseline.passed} passed in {testing.historical_backend_baseline.duration_seconds}s. This is a baseline, not current validation.</p>}{stages.length > 0 && <div className="mt-4 space-y-1">{stages.map(stage => { const status = stage.status || 'pending'; const done = ['complete','completed','success','succeeded'].includes(status); const failed = ['failed','error'].includes(status); return <div className="vv-status-row" key={stage.stage_id || stage.id}><span>{failed ? <XCircle size={14}/> : done ? <CheckCircle2 size={14}/> : <Circle size={14}/>}</span><span>{stage.number ? `${stage.number}. ` : ''}{stage.name || stage.stage_id || stage.id}</span><span className="ml-auto">{status}</span></div> })}</div>}</div> }

function LogPanel({ query }) { const records = query.data?.payload?.events || query.data?.events || []; return <div><PageTitle eyebrow="OBSERVE" title="Live Logs" action={<Button variant="secondary" onClick={() => query.refetch()}><RefreshCw size={14}/> Refresh</Button>}/><section className="vv-panel"><div className="vv-log-banner"><span className="vv-live-dot"/> Live diagnostic stream · polling every 2.5 seconds while this panel is open</div>{query.isPending ? <p className="vv-copy">Loading live diagnostics…</p> : query.isError ? <div className="vv-status-row error"><XCircle size={16}/><span>{query.error?.message || 'Unable to load diagnostic events.'}</span></div> : records.length ? <div className="vv-log-stream">{records.map((record, index) => <div className="vv-log-row" key={`${record.timestamp}-${record.event}-${index}`}><div className="text-white/45">{record.event?.includes('error') || record.event?.includes('failed') ? <XCircle size={16}/> : record.event?.includes('completed') || record.event?.includes('uploaded') ? <CheckCircle2 size={16}/> : <Activity size={16}/>}</div><div className="vv-log-main"><div><strong className="text-white/75">{record.event || 'diagnostic event'}</strong><span className="vv-log-time">{record.timestamp ? new Date(record.timestamp).toLocaleString() : '—'}</span></div><p>{record.error_message || record.detail || record.reason || record.stage || 'Lifecycle event recorded.'}</p><div className="vv-error-meta"><span>request {record.request_id || '—'}</span>{record.status_code != null && <span>HTTP {record.status_code}</span>}{record.duration_ms != null && <span>{record.duration_ms} ms</span>}{record.stage && <span>stage {record.stage}</span>}</div></div></div>)}</div> : <p className="vv-copy">No diagnostic events were returned for the selected window.</p>}</section></div> }

function ErrorPanel({ query }) { const records = query.data?.payload?.events || query.data?.events || []; return <div><PageTitle eyebrow="OBSERVE" title="Error Reports" action={<Button variant="secondary" onClick={() => query.refetch()}><RefreshCw size={14}/> Refresh</Button>}/><section className="vv-panel">{query.isPending ? <p className="vv-copy">Loading persisted errors…</p> : query.isError ? <div className="vv-status-row error"><XCircle size={16}/><span>{query.error?.message || 'Unable to load persisted errors.'}</span></div> : records.length ? <div className="vv-log-stream">{records.map((record, index) => <div className="vv-log-row" key={`${record.timestamp}-${record.request_id}-${index}`}><div className="text-red-300/80"><XCircle size={17}/></div><div className="vv-log-main"><div><strong className="text-red-100/80">{record.event || 'error'}</strong><span className="vv-log-time">{record.timestamp ? new Date(record.timestamp).toLocaleString() : '—'}</span></div><p>{record.error_message || record.detail || record.reason || 'No sanitized error message was recorded.'}</p><div className="vv-error-meta"><span>request {record.request_id || '—'}</span>{record.error_type && <span>{record.error_type}</span>}{record.status_code != null && <span>HTTP {record.status_code}</span>}{record.source_revision && <span>rev {record.source_revision.slice(0,12)}</span>}</div></div></div>)}</div> : <p className="vv-copy">No persisted errors were returned for the selected window.</p>}</section></div> }

function Profile({ session, signOut, avatar }) { const user = session?.user || {}; const meta = user.user_metadata || {}; return <div><PageTitle eyebrow="ACCOUNT" title="Developer Profile"/><section className="vv-panel"><div className="flex flex-wrap items-center gap-4">{avatar}<div className="min-w-0"><div className="truncate text-lg font-semibold">{meta.full_name || meta.name || user.email?.split('@')[0] || 'Developer'}</div><div className="truncate text-sm text-[var(--vv-muted)]">{user.email || 'Authenticated developer'}</div><div className="mt-1 text-[11px] text-[var(--vv-muted)]">Developer role is enforced by Supabase application metadata.</div></div></div><div className="mt-5 flex flex-wrap gap-2"><Button variant="secondary" onClick={() => signOut()}><LogOut size={15}/> Sign out</Button></div></section></div> }

function Data({ label, value }) { return <div><div className="vv-eyebrow">{label}</div><div className="mt-1 text-sm">{value || '—'}</div></div>}
function DocLink({ title, href, detail }) { return <a href={href} target="_blank" rel="noreferrer" className="border border-[var(--vv-border)] p-4 no-underline transition hover:border-[var(--vv-border-strong)]"><div className="font-medium">{title}</div><div className="mt-1 text-xs text-[var(--vv-muted)]">{detail}</div></a> }
function Docs() { return <div><PageTitle eyebrow="SOURCE" title="Methodology & Documentation"/><div className="grid gap-3 md:grid-cols-2">{Object.entries(DOCS).map(([key, href]) => <DocLink key={key} title={key} href={href} detail={href}/>)}</div></div> }
function MvpBoard({ checks, setChecks, percent, complete, total }) { const [open, setOpen] = useState(() => new Set(['P0','P1'])); const allOpen = open.size === phases.length; const togglePhase = id => setOpen(current => { const next = new Set(current); next.has(id) ? next.delete(id) : next.add(id); return next }); const toggle = id => setChecks(current => ({...current,[id]:!current[id]})); return <div><PageTitle eyebrow="DELIVERY" title="Fastest Path to MVP" action={<div className="flex gap-2"><Button variant="secondary" onClick={() => setOpen(allOpen ? new Set() : new Set(phases.map(p=>p.id)))}>{allOpen ? 'Collapse All' : 'Expand All'}</Button><Button variant="secondary" onClick={() => setChecks({})}>Reset Checks</Button></div>}/><section className="vv-panel mb-4"><div className="vv-eyebrow">MVP Execution Board</div><div className="mt-1 text-2xl font-semibold">{percent}% complete</div><p className="vv-copy mt-1">{complete} of {total} engineering tasks checked</p></section><div className="space-y-2">{phases.map(phase => { const done=phase.tasks.filter(([id])=>checks[id]).length; const isOpen=open.has(phase.id); return <section className="vv-panel" key={phase.id}><button className="flex w-full items-center gap-3 text-left" onClick={() => togglePhase(phase.id)} aria-expanded={isOpen}>{isOpen?<ChevronDown size={17}/>:<ChevronRight size={17}/>}<span className="vv-eyebrow">{phase.id}</span><strong className="text-sm">{phase.title}</strong><span className="ml-auto text-xs text-[var(--vv-muted)]">{done}/{phase.tasks.length}</span></button>{isOpen&&<div className="mt-4 space-y-1">{phase.tasks.map(([id,label,owner])=><button key={id} onClick={()=>toggle(id)} className="vv-status-row w-full text-left"><span>{checks[id]?<CircleCheck size={16}/>:<Circle size={16}/>}</span><span className={checks[id]?'line-through opacity-60':''}>{label}</span><span className="ml-auto text-[10px] uppercase tracking-wider text-[var(--vv-muted)]">{owner}</span></button>)}</div>}<p className="vv-copy mt-3">{phase.detail}</p></section>})}</div></div> }
