import { useEffect, useState } from 'react'
import { Code2, LoaderCircle, Menu, Terminal, UserRound, X, LogOut } from 'lucide-react'
import { useQuery } from '@tanstack/react-query'
import { getHealth } from '../lib/api'
import { supabase } from '../lib/supabase'
import DeveloperEngineeringStatus from './DeveloperEngineeringStatus'
import './SiteHeader.css'

const navigation = [['Product', '#product'], ['How it works', '#workflow'], ['Technology', '#technology'], ['Use cases', '#use-cases'], ['Resources', '#briefing']]
function Logo() { return <a href="/voxvector/" className="vv-logo-lockup group no-underline" aria-label="VoxVector home"><img src="/voxvector/voxvector-icon-final-color.png.PNG" alt="" className="vv-logo-icon"/><img src="/voxvector/VoxVector-logo-word.png" alt="VoxVector" className="vv-logo-wordmark"/></a> }
function IconButton({ href, label, children, onClick }) { const className='inline-flex h-9 w-9 shrink-0 items-center justify-center border-0 bg-transparent p-0 text-white/55 transition hover:text-white'; return href ? <a href={href} target="_blank" rel="noreferrer" className={className} aria-label={label} title={label}>{children}</a> : <button type="button" onClick={onClick} className={className} aria-label={label} title={label}>{children}</button> }
function DeveloperToolbar({ mobileMenuButton }) { const [signingOut,setSigningOut]=useState(false); const signOut=async()=>{if(!supabase||signingOut)return;setSigningOut(true);const{error}=await supabase.auth.signOut();if(error){setSigningOut(false);return}window.location.href='/voxvector/developer/'}; return <header className="vv-public-header vv-developer-header sticky top-0 z-[200] border-b border-[var(--vv-border)] bg-[var(--vv-bg)]/95 backdrop-blur-xl"><div className="vv-header-inner relative mx-auto flex h-16 w-full max-w-[1440px] items-center justify-between px-4 sm:px-6 lg:px-8"><div className="flex h-full min-w-[100px] items-center">{mobileMenuButton||<button type="button" className="inline-flex h-9 w-9 items-center justify-center border-0 bg-transparent p-0 text-white/65" aria-label="Open console navigation"><Menu size={18}/></button>}</div><a href="/voxvector/developer/" aria-label="VoxVector Developer Console" className="vv-developer-logo absolute left-1/2 top-1/2 inline-flex h-10 w-10 -translate-x-1/2 -translate-y-1/2 items-center justify-center no-underline"><img src="/voxvector/assets/voxvector-icon-final-color.png" alt="VoxVector" className="h-9 w-9 object-contain"/></a><div className="flex h-full min-w-[100px] items-center justify-end gap-3"><IconButton href="/voxvector/sitemap.xml" label="VoxVector site map"><Terminal size={18}/></IconButton><IconButton href="/voxvector/developer/#profile" label="Developer profile"><UserRound size={18}/></IconButton><IconButton label={signingOut?'Signing out':'Sign out'} onClick={signOut}>{signingOut?<LoaderCircle size={18} className="animate-spin"/>:<LogOut size={18}/>}</IconButton></div></div></header> }
function ApiStartupWindow(){const[visible,setVisible]=useState(true);const developer=window.location.pathname.replace(/\/+$/,'')==='/voxvector/developer';const health=useQuery({queryKey:['header-api-health'],queryFn:getHealth,enabled:developer,retry:false,refetchInterval:q=>q.state.data?.payload?.status==='ok'?false:2000,staleTime:0});useEffect(()=>{if(!developer)return;if(health.data?.payload?.status==='ok'){const t=window.setTimeout(()=>setVisible(false),1100);return()=>window.clearTimeout(t)}},[developer,health.data?.payload?.status]);if(!developer||!visible)return null;const online=health.data?.payload?.status==='ok',failed=Boolean(health.error)&&!health.isFetching;return <div className={`vv-api-startup ${online?'ready':''}`} role="status" aria-live="polite"><div className="vv-api-startup__inner"><span className={`vv-api-startup__icon ${online?'ready':''}`}>{online?'✓':<LoaderCircle size={17} className="vv-api-startup__spinner"/>}</span><span className="vv-api-startup__copy"><strong>{online?'VoxVector API ready':failed?'Reconnecting to VoxVector API':'Initializing VoxVector API'}</strong><span>{online?'Secure analysis services are ready.':failed?'The API may be waking from sleep. Retrying automatically.':'Waking services and checking runtime health…'}</span></span></div></div>}
export default function SiteHeader({userMenu=null,actions=null,mobileActions=null,mobileMenuButton=null,active=null}){const[menuOpen,setMenuOpen]=useState(false);const developer=typeof window!=='undefined'&&(window.location.pathname.replace(/\/+$/,'')==='/voxvector/developer'||window.location.hash==='#/developer');if(developer)return <><DeveloperToolbar mobileMenuButton={mobileMenuButton}/><ApiStartupWindow/><DeveloperEngineeringStatus/></>;return <><header className="vv-public-header sticky top-0 z-[200] border-b border-[var(--vv-border)] bg-[var(--vv-bg)]/90 backdrop-blur-xl"><div className="vv-header-inner mx-auto flex h-16 max-w-[1440px] items-center justify-between gap-7 px-5 lg:px-10"><Logo/><nav className="hidden items-center gap-[2.35rem] text-sm font-medium text-white/[.54] lg:flex" aria-label="Primary navigation">{navigation.map(([label,href])=><a key={label} href={href} aria-current={active===label?'page':undefined} className="transition-colors hover:text-white no-underline">{label}</a>)}<a href="/voxvector/developer" className="inline-flex items-center gap-2 transition-colors hover:text-white no-underline"><Terminal size={15}/>Developer</a></nav><div className="hidden items-center gap-3 md:flex">{actions||<a href="https://github.com/darenprince/darenprince-author/tree/main/voxvector" target="_blank" rel="noreferrer" className="inline-flex h-10 items-center gap-2 border border-[var(--vv-border-strong)] bg-[var(--vv-panel)] px-4 text-sm font-semibold text-white/[.78] no-underline"><Code2 size={16}/>GitHub</a>}{userMenu}</div>{mobileMenuButton||<button type="button" className="inline-flex h-10 w-10 items-center justify-center border border-[var(--vv-border)] text-white lg:hidden" aria-label={menuOpen?'Close navigation menu':'Open navigation menu'} aria-expanded={menuOpen} onClick={()=>setMenuOpen(v=>!v)}>{menuOpen?<X size={20}/>:<Menu size={20}/>}</button>}</div>{menuOpen&&<nav className="border-t border-[var(--vv-border)] bg-[var(--vv-bg)] px-5 py-5 lg:hidden" aria-label="Mobile navigation">{navigation.map(([label,href])=><a key={label} href={href} onClick={()=>setMenuOpen(false)} className="block border-b border-[var(--vv-border)] py-4 text-base font-medium text-white/[.68] no-underline">{label}</a>)}<a href="/voxvector/developer" onClick={()=>setMenuOpen(false)} className="flex items-center gap-2 py-4 text-base font-semibold text-white no-underline"><Terminal size={16}/>Developer</a>{mobileActions}{userMenu&&<div className="border-t border-[var(--vv-border)] pt-4">{userMenu}</div>}</nav>}</header><ApiStartupWindow/></>}
