import { useEffect, useState } from 'react'
import { Activity, BookOpen, Code2, Cpu, FileText, Layers3, LoaderCircle, Map, Terminal, UserRound, LogOut } from 'lucide-react'
import { useQuery } from '@tanstack/react-query'
import { getHealth } from '../lib/api'
import { supabase } from '../lib/supabase'
import DeveloperEngineeringStatus from './DeveloperEngineeringStatus'
import Sheet from './ui/Sheet'
import SharpIcon from './SharpIcon'
import './SiteHeader.css'
import './Typography.css'

const navigation = [
  { label: 'Product', href: '#product', Icon: Layers3 },
  { label: 'How it works', href: '#workflow', Icon: Activity },
  { label: 'Technology', href: '#technology', Icon: Cpu },
  { label: 'Use cases', href: '#use-cases', Icon: FileText },
  { label: 'Resources', href: '#briefing', Icon: BookOpen },
]
function Logo() { return <a href="/voxvector/" className="vv-logo-lockup group no-underline" aria-label="VoxVector home"><img src="/voxvector/voxvector-icon-final-color.png.PNG" alt="" className="vv-logo-icon"/><img src="/voxvector/VoxVector-logo-word.png" alt="VoxVector" className="vv-logo-wordmark"/></a> }
function MenuGlyph({ open = false }) { return <span className={`vv-menu-glyph${open ? ' vv-menu-glyph--close' : ''}`} aria-hidden="true"><span/><span/></span> }
function MenuTrigger({ open, onClick, label = 'Open navigation' }) { return <button type="button" className="vv-menu-trigger inline-flex h-9 w-9 shrink-0 items-center justify-center border-0 bg-transparent p-0" onClick={onClick} aria-label={open ? 'Close navigation' : label} aria-expanded={open}><MenuGlyph open={open}/></button> }
function GitHubMark({ size=17 }) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 2C6.477 2 2 6.586 2 12.242c0 4.523 2.865 8.356 6.839 9.71.5.095.682-.223.682-.496 0-.244-.009-.892-.014-1.75-2.782.62-3.369-1.37-3.369-1.37-.455-1.183-1.11-1.498-1.11-1.498-.908-.64.069-.627.069-.627 1.004.072 1.532 1.056 1.532 1.056.892 1.567 2.341 1.114 2.91.852.091-.665.349-1.114.635-1.37-2.22-.26-4.555-1.139-4.555-5.07 0-1.12.39-2.035 1.03-2.753-.103-.26-.447-1.307.098-2.724 0 0 .84-.277 2.75 1.052A9.33 9.33 0 0 1 12 6.85c.85.004 1.706.118 2.505.347 1.91-1.33 2.748-1.052 2.748-1.052.546 1.417.202 2.464.1 2.724.64.718 1.028 1.633 1.028 2.753 0 3.941-2.339 4.807-4.566 5.062.359.32.678.952.678 1.919 0 1.386-.012 2.505-.012 2.845 0 .276.18.596.688.495C19.14 20.594 22 16.763 22 12.242 22 6.586 17.523 2 12 2Z"/></svg> }
function IconButton({ href, label, children, onClick }) { const className='inline-flex h-9 w-9 shrink-0 items-center justify-center border-0 bg-transparent p-0 text-white/55 transition hover:text-white'; return href ? <a href={href} target="_blank" rel="noreferrer" className={className} aria-label={label} title={label}>{children}</a> : <button type="button" onClick={onClick} className={className} aria-label={label} title={label}>{children}</button> }
function DeveloperToolbar({ mobileMenuButton, actions = null }) { return <header className="vv-public-header vv-developer-header sticky top-0 z-[200] border-b border-[var(--vv-border)] bg-[var(--vv-bg)]/95 backdrop-blur-xl"><div className="vv-header-inner relative mx-auto flex h-14 w-full max-w-[1440px] items-center justify-between px-4 sm:px-6 lg:px-8"><div className="flex h-full min-w-[100px] items-center">{mobileMenuButton ? <span className="vv-menu-proxy">{mobileMenuButton}</span> : <MenuTrigger label="Open console navigation"/>}</div><a href="/voxvector/developer/" aria-label="VoxVector Developer Console" className="vv-developer-logo absolute left-1/2 top-1/2 inline-flex h-8 w-8 -translate-x-1/2 -translate-y-1/2 items-center justify-center no-underline"><img src="/voxvector/assets/voxvector-icon-final-color.png" alt="VoxVector" className="h-7 w-7 object-contain"/></a><div className="flex h-full min-w-[100px] items-center justify-end gap-1">{actions}</div></div></header> }
function ApiStartupWindow(){const[visible,setVisible]=useState(true);const developer=window.location.pathname.replace(/\/+$/,'')==='/voxvector/developer';const health=useQuery({queryKey:['header-api-health'],queryFn:getHealth,enabled:developer,retry:false,refetchInterval:q=>q.state.data?.payload?.status==='ok'?false:2000,staleTime:0});useEffect(()=>{if(!developer)return; if(health.data?.payload?.status==='ok'){const t=window.setTimeout(()=>setVisible(false),1100);return()=>window.clearTimeout(t)}},[developer,health.data?.payload?.status]);if(!developer||!visible)return null;const online=health.data?.payload?.status==='ok',failed=Boolean(health.error)&&!health.isFetching;return <div className={`vv-api-startup ${online?'ready':''}`} role="status" aria-live="polite"><div className="vv-api-startup__inner"><span className={`vv-api-startup__icon ${online?'ready':''}`}>{online?'✓':<LoaderCircle size={17} className="vv-api-startup__spinner"/>}</span><span className="vv-api-startup__copy"><strong>{online?'VoxVector API ready':failed?'Reconnecting to VoxVector API':'Initializing VoxVector API'}</strong><span>{online?'Secure analysis services are ready.':failed?'The API may be waking from sleep. Retrying automatically.':'Waking services and checking runtime health…'}</span></span></div></div>}
export default function SiteHeader({userMenu=null,actions=null,mobileActions=null,mobileMenuButton=null,active=null}){const[menuOpen,setMenuOpen]=useState(false);const developer=typeof window!=='undefined'&&(window.location.pathname.replace(/\/+$/,'')==='/voxvector/developer'||window.location.hash==='#/developer');if(developer)return <><DeveloperToolbar mobileMenuButton={mobileMenuButton} actions={actions}/><ApiStartupWindow/></>;return <><header className="vv-public-header sticky top-0 z-[200] border-b border-[var(--vv-border)] bg-[var(--vv-bg)]/90 backdrop-blur-xl"><div className="vv-header-inner mx-auto flex h-14 max-w-[1440px] items-center justify-between gap-5 px-4 sm:px-6 lg:px-10"><Logo/><nav className="vv-public-primary-nav hidden items-center gap-[1.45rem] text-sm font-medium text-white/[.54] lg:flex" aria-label="Primary navigation">{navigation.map(({label,href,Icon})=><a key={label} href={href} aria-current={active===label?'page':undefined} className="transition-colors hover:text-white no-underline"><Icon className="vv-public-nav-icon" size={14} strokeWidth={1.8} />{label}</a>)}<a href="/voxvector/developer" className="inline-flex items-center gap-2 transition-colors hover:text-white no-underline"><SharpIcon name="ai-science-spark" size={15}/>Developer</a></nav><div className="hidden items-center gap-3 md:flex">{actions||<a href="https://github.com/darenprince/darenprince-author/tree/main/voxvector" target="_blank" rel="noreferrer" className="inline-flex h-9 items-center gap-2 border border-[var(--vv-border-strong)] bg-[var(--vv-panel)] px-3.5 text-sm font-semibold text-white/[.78] no-underline"><GitHubMark size={15}/>GitHub</a>}<IconButton href="https://github.com/darenprince/darenprince-author/tree/main/voxvector" label="VoxVector source on GitHub"><GitHubMark size={17}/></IconButton><IconButton href="/voxvector/developer" label="VoxVector account and developer login"><UserRound size={17} strokeWidth={1.9}/></IconButton>{userMenu}</div>{mobileMenuButton||<MenuTrigger open={menuOpen} onClick={()=>setMenuOpen(v=>!v)}/>}</div></header><Sheet open={menuOpen} onOpenChange={setMenuOpen} ariaLabel="VoxVector navigation"><div className="vv-sheet-head"><span className="vv-eyebrow">Navigation</span><MenuTrigger open onClick={()=>setMenuOpen(false)} label="Close navigation"/></div><nav className="vv-public-mobile-nav" aria-label="Mobile navigation">{navigation.map(({label,href,Icon})=><a key={label} href={href} onClick={()=>setMenuOpen(false)}><Icon className="vv-public-nav-icon" size={17} strokeWidth={1.8}/>{label}</a>)}<a href="/voxvector/developer" onClick={()=>setMenuOpen(false)} className="vv-mobile-nav-action"><SharpIcon name="ai-science-spark" size={17}/>Developer</a></nav>{mobileActions}<div className="vv-mobile-nav-meta">{userMenu}</div></Sheet><ApiStartupWindow/></>}
