import { useEffect, useRef, useState } from 'react'
import { Maximize2, Minus, Plus, Radio, ZoomIn } from 'lucide-react'
import './Spectrogram.css'

const TAU = Math.PI * 2
function pitchState(hz) { if (!Number.isFinite(hz) || hz <= 0) return ['—','neutral']; if (hz < 85) return ['LOW','low']; if (hz <= 255) return ['VOICE','voice']; return ['HIGH','high'] }
function estimatePitch(data, sampleRate) { let rms=0; for(let i=0;i<data.length;i+=1) rms+=data[i]*data[i]; rms=Math.sqrt(rms/data.length); if(rms<.008)return 0; const minLag=Math.floor(sampleRate/500), maxLag=Math.min(Math.floor(sampleRate/60),data.length-2); let best=0,bestCorr=0; for(let lag=minLag;lag<=maxLag;lag+=1){let corr=0;for(let i=0;i<data.length-lag;i+=2)corr+=data[i]*data[i+lag];if(corr>bestCorr){bestCorr=corr;best=lag}} return best?sampleRate/best:0 }
function magnitudeAt(data,bin,size){let re=0,im=0;for(let n=0;n<size;n+=1){const w=.5-.5*Math.cos(TAU*n/(size-1)),a=TAU*bin*n/size,v=data[n]*w;re+=v*Math.cos(a);im-=v*Math.sin(a)}return Math.sqrt(re*re+im*im)/size}
function buildSpectrogram(buffer,sampleRate,columns=220,rows=96){const data=buffer.getChannelData(0),fft=256,out=new Uint8ClampedArray(columns*rows);for(let x=0;x<columns;x+=1){const center=Math.floor((x/Math.max(1,columns-1))*Math.max(0,data.length-1)),start=Math.max(0,Math.min(data.length-fft,center-128)),frame=new Float32Array(fft);frame.set(data.subarray(start,Math.min(data.length,start+fft)));for(let y=0;y<rows;y+=1){const freq=y/(rows-1)*(sampleRate/2),bin=Math.max(1,Math.min(127,Math.round(freq*fft/sampleRate))),mag=magnitudeAt(frame,bin,fft),db=20*Math.log10(Math.max(mag,1e-5));out[(rows-1-y)*columns+x]=Math.max(4,Math.min(255,Math.round((db+65)*4.4)))}}return{data:out,columns,rows}}
function paint(canvas,image,zoom,cursor,sampleRate){if(!canvas||!image)return;const dpr=Math.min(2,window.devicePixelRatio||1),rect=canvas.getBoundingClientRect();canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,rect.width,rect.height);const off=document.createElement('canvas');off.width=image.columns;off.height=image.rows;const octx=off.getContext('2d'),pixels=octx.createImageData(image.columns,image.rows);for(let i=0;i<image.data.length;i+=1){const v=image.data[i]/255;pixels.data[i*4]=Math.round(42+v*210);pixels.data[i*4+1]=Math.round(36+v*178);pixels.data[i*4+2]=Math.round(29+v*126);pixels.data[i*4+3]=Math.round(38+v*217)}octx.putImageData(pixels,0,0);ctx.imageSmoothingEnabled=false;const scaledWidth=rect.width*zoom,x=-((cursor||0)*(scaledWidth-rect.width));ctx.drawImage(off,x,0,scaledWidth,rect.height);ctx.strokeStyle='rgba(245,243,238,.12)';ctx.lineWidth=1;[1000,2000,4000,8000,16000].filter(f=>f<sampleRate/2).forEach(f=>{const y=rect.height*(1-f/(sampleRate/2));ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(rect.width,y);ctx.stroke()})}

export default function Spectrogram({audioBuffer,analyser,playing,currentTime=0,duration=0,sampleRate=48000}){const canvasRef=useRef(null),[image,setImage]=useState(null),[zoom,setZoom]=useState(1),[pitch,setPitch]=useState(0),[cursor,setCursor]=useState(0);useEffect(()=>{let cancelled=false;if(!audioBuffer){setImage(null);return undefined}const id=setTimeout(()=>{const result=buildSpectrogram(audioBuffer,audioBuffer.sampleRate||sampleRate);if(!cancelled)setImage(result)},20);return()=>{cancelled=true;clearTimeout(id)}},[audioBuffer,sampleRate]);useEffect(()=>{paint(canvasRef.current,image,zoom,cursor,audioBuffer?.sampleRate||sampleRate)},[image,zoom,cursor,audioBuffer,sampleRate]);useEffect(()=>{if(!analyser||!playing)return undefined;const data=new Float32Array(analyser.fftSize);let raf=0;const tick=()=>{analyser.getFloatTimeDomainData(data);setPitch(estimatePitch(data,analyser.context?.sampleRate||sampleRate));raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf)},[analyser,playing,sampleRate]);useEffect(()=>{if(duration)setCursor(Math.min(1,Math.max(0,currentTime/duration)))},[currentTime,duration]);const[pitchLabel,pitchClass]=pitchState(pitch),maxHz=Math.round((audioBuffer?.sampleRate||sampleRate)/2);return <section className="vv-spectrogram" aria-label="Audio spectrogram and pitch analysis"><div className="vv-spectrogram-head"><div><span className="vv-eyebrow">SPECTRAL ANALYSIS</span><h3>Frequency × time</h3></div><div className="vv-spectrogram-tools"><span className={`vv-pitch-chip ${pitchClass}`}><Radio size={12}/>{pitch?`${pitch.toFixed(1)} Hz`:'PITCH —'} <b>{pitchLabel}</b></span><button type="button" onClick={()=>setZoom(Math.max(1,zoom-.5))} aria-label="Zoom out"><Minus size={13}/></button><span className="vv-zoom-value">{zoom.toFixed(1)}×</span><button type="button" onClick={()=>setZoom(Math.min(4,zoom+.5))} aria-label="Zoom in"><Plus size={13}/></button><button type="button" onClick={()=>setZoom(1)} aria-label="Reset zoom"><Maximize2 size={13}/></button></div></div><div className="vv-spectrogram-body"><canvas ref={canvasRef} onClick={e=>{const r=e.currentTarget.getBoundingClientRect();setCursor(Math.max(0,Math.min(1,e.clientX/r.width)))}}/><div className="vv-spectrum-y"><span>{(maxHz/1000).toFixed(0)} kHz</span><span>8 kHz</span><span>4 kHz</span><span>2 kHz</span><span>1 kHz</span><span>0</span></div><div className="vv-spectrum-cursor" style={{left:`${cursor*100}%`}}/></div><div className="vv-spectrogram-axis"><span>0:00</span><span>{duration?`${Math.round(duration/2)}s`:'TIME'}</span><span>{duration?`${Math.round(duration)}s`:'→'}</span></div><div className="vv-spectrogram-footer"><span><ZoomIn size={12}/> High detail · click to position · zoom 1×–4×</span><span className={playing?'live':''}>{playing?'● LIVE SPECTRAL TRACKING':'STATIC SPECTROGRAM'}</span></div></section>}
