import { LogOut, ShieldCheck } from 'lucide-react'
import AuthGate from './AuthGate'
import AccountProfileEditor, { useAccountProfile } from './DeveloperProfileEditor'
import Button from './ui/Button'

export default function UserWorkspace() {
  return <AuthGate allowedRoles={['user']} onBack={() => { window.location.href = '/voxvector/' }}>
    {({ session, signOut, role }) => <Workspace session={session} signOut={signOut} role={role}/>} 
  </AuthGate>
}

function Workspace({ session, signOut, role }) {
  const user = session?.user || {}
  const metadata = user.user_metadata || {}
  const profileQuery = useAccountProfile(session)
  const displayName = profileQuery.data?.display_name || metadata.full_name || metadata.name || user.email?.split('@')[0] || 'VoxVector user'
  return <div className="min-h-screen bg-[var(--vv-bg)] text-white"><header className="border-b border-[var(--vv-border)] bg-[var(--vv-bg)]/95 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-[1200px] items-center justify-between px-5 sm:px-8"><a href="/voxvector/" className="inline-flex items-center gap-2 no-underline" aria-label="VoxVector home"><img src="/voxvector/voxvector_logo_icon.png" alt="" className="h-8 w-8 object-contain"/><img src="/voxvector/VoxVector-logo-word.png" alt="VoxVector" className="h-6 w-auto object-contain"/></a><Button variant="secondary" onClick={signOut}><LogOut size={15}/>Sign out</Button></div></header><main className="mx-auto max-w-[1200px] px-5 py-14 sm:px-8 sm:py-20"><div className="vv-eyebrow">USER WORKSPACE</div><h1 className="mt-2 max-w-3xl text-4xl font-semibold tracking-[-.045em] sm:text-5xl">Welcome, {displayName}</h1><p className="mt-4 max-w-2xl text-base leading-7 text-white/50">Your VoxVector account is active. This protected workspace is the canonical destination for approved user accounts while user-facing analysis workflows are connected to the same authenticated product architecture.</p><div className="mt-10 grid gap-4 lg:grid-cols-[minmax(0,1.35fr)_minmax(280px,.65fr)]"><AccountProfileEditor session={session} profileQuery={profileQuery} signOut={signOut} embedded/><section className="vv-panel"><div className="flex items-center gap-3"><ShieldCheck size={20} className="text-[var(--vv-accent-bright)]"/><div><div className="vv-eyebrow">ACCESS</div><h2 className="mt-1 text-lg font-semibold">Protected session</h2></div></div><p className="mt-6 text-sm leading-6 text-white/50">VoxVector restored this session through Supabase Auth and admitted it from trusted application role metadata. Developer Console routes remain independently restricted.</p><dl className="mt-5 grid gap-4 text-sm"><div><dt className="text-white/40">Trusted role</dt><dd className="mt-1 text-white/75">{role}</dd></div><div><dt className="text-white/40">Account ID</dt><dd className="mt-1 break-all font-mono text-xs text-white/55">{user.id || '—'}</dd></div></dl><div className="mt-5 inline-flex items-center gap-2 text-xs font-semibold text-emerald-200/80"><span className="h-1.5 w-1.5 rounded-full bg-emerald-300"/>Authenticated</div></section></div><div className="mt-8 flex flex-wrap gap-3"><a href="/voxvector/" className="inline-flex h-10 items-center border border-[var(--vv-border-strong)] px-4 text-sm font-semibold text-white/70 no-underline transition hover:text-white">Return to VoxVector</a><a href="/docs/crownlabsbible/docs/viewer.html?doc=../04-product-dossiers/VoxVector/overview.md" className="inline-flex h-10 items-center border border-[var(--vv-border-strong)] px-4 text-sm font-semibold text-white/70 no-underline transition hover:text-white">Product documentation</a></div></main></div>
}
