[build]
  publish = "./"
  command = "node scripts/generate-env.js && sass scss/styles.scss assets/styles.css"

# Remove or comment this out ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
# [[plugins]]
#   package = "@netlify/plugin-emails"

# [[plugins]]
#   package = "@netlify/plugin-sitemap"

# [[plugins]]
#   package = "@helloample/netlify-plugin-replace"
