const fs = require('fs');
const path = require('path');

const {
  SUPABASE_URL = '',
  SUPABASE_DATABASE_URL = '',
  SUPABASE_ANON_KEY = '',
  SUPABASE_PUBLIC_ANON_KEY = '',
  SUPABASE_SERVICE_ROLE_KEY = ''
} = process.env;

const resolvedUrl = SUPABASE_URL || SUPABASE_DATABASE_URL;
const resolvedAnonKey = SUPABASE_ANON_KEY || SUPABASE_PUBLIC_ANON_KEY;

if (!resolvedUrl || !resolvedAnonKey) {
  console.warn('Warning: SUPABASE_URL/SUPABASE_DATABASE_URL and/or SUPABASE_ANON_KEY are not set.');
}

if (SUPABASE_SERVICE_ROLE_KEY) {
  console.info('Supabase service role key detected; it will not be written to the client bundle.');
}

const envPayload = {
  SUPABASE_URL: resolvedUrl,
  SUPABASE_DATABASE_URL: resolvedUrl,
  SUPABASE_ANON_KEY: resolvedAnonKey
};

const content = `// Generated by scripts/generate-env.js
export const SUPABASE_URL = ${JSON.stringify(resolvedUrl)};
export const SUPABASE_DATABASE_URL = ${JSON.stringify(resolvedUrl)};
export const SUPABASE_ANON_KEY = ${JSON.stringify(resolvedAnonKey)};

if (typeof window !== 'undefined') {
  window._env_ = ${JSON.stringify(envPayload, null, 2)};
}
`;

const dest = path.join(__dirname, '..', 'assets', 'js', 'env.js');
fs.mkdirSync(path.dirname(dest), { recursive: true });
fs.writeFileSync(dest, content);
console.log('Environment file generated at', dest);
